version: 2.1
orbs: 
  python: circleci/python@2.0.3
#   snyk: snyk/snyk@0.0.8
jobs:
  build_test:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r "SysID Addon"/requirements.txt
#       - snyk/scan
workflows:
  test_my_app:
    jobs:
      - build_test

