version: 2.1
orbs:
  snyk: snyk/snyk@0.0.11
jobs:
  vulnerability_scan:
    docker:
      - image: circleci/node:12
    steps:
      - snyk/scan
workflows:
  build_test:
    jobs:
      - vulnerability_scan
